#!/bin/sh
## $Id: getpgpkey,v 1.2 2003/03/20 04:03:35 yozo Exp $

PATH=${HOME}/bin:/usr/local/bin:/usr/bin:/bin

FETCHCMD="w3m -dump"
KEYSERVER=pgp.nic.ad.jp
PORT=11371
SERVERPATH="/pks/lookup?op=get&search="

usage(){
  echo "usage: $0 [-help |-host host] key  (where key is 0x...)" 1>&2
}

if [ $# -le 0 ]; then
  usage
  exit 10
fi

while [ $# -gt 1 ]; do
  case "$1" in
    -he*)
      usage
      exit 20
      ;;
    -ho*)
      KEYSERVER="$2"
      shift
      shift
      ;;
    -*)
      echo "$0: unknown option ($1)" 1>&2
      usage
      exit 30
      ;;
  esac
done

if [ ! $# -eq 1 ]; then
  usage
  exit 40
fi

URL="http://${KEYSERVER}:${PORT}${SERVERPATH}"
${FETCHCMD} "${URL}$1"
