#!/bin/sh
## $Id: getpgpkey,v 1.1 2003/03/02 11:07:59 yozo Exp $

PATH=${HOME}/bin:/usr/local/bin:/usr/bin:/bin

FETCHCMD="w3m -dump"
URL="http://pgp.nic.ad.jp:11371/pks/lookup?op=get&search="

usage(){
  echo "usage: $0 key  (where key is 0x...)" 1>&2
}

if [ ! $# -eq 1 ]; then
  usage
  exit 10
fi

${FETCHCMD} "${URL}$1"
