#!/bin/sh
## $Id: make-xenocara,v 1.11 2012/08/19 06:13:21 yozo Exp $
## make-xenocara script based on make-xf4
## if you wanna record the output, type
##     (make-xenocara 2>&1 ) > logfile &
## and see logfile.
## -- yozo.  Mon Apr 30 12:04:48 JST 2007

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin

LOGDIR=/usr/local/tmp
XSRCDIR=/usr/xenocara
OBJDIR=/usr/xobj
OBJOLDDIR=${OBJDIR}/.OLD
## OBJBUILDDIR=${OBJDIR}/XF4
EXISTS_OBJDIR="YES" ## assumes obj dir by default
XDMDIR=/etc/X11/xenodm
XDMOLDDIR=/etc/X11/xenodm_old
## DESTDIR=/var/tmp/xenocara
## XENOCARA_TOP and XENOCARA_OBJDIR defined in /usr/X11R6/share/mk/bsd.xorg.mk.
## /usr/X11R6/share/mk/bsd.xorg.mk revised.
## XENOCARA_TOP=/usr/src/xenocara
## XENOCARA_OBJDIR=/usr/xobj

echo -n "$0: "
date
echo -n "$0: "
uname -a
echo
ls -alt ${LOGDIR}
df -k
echo

## miscellaneous checking before compiling.
if [ -d ${XSRCDIR} ] ; then
  echo "$0: ${XSRCDIR} exists. progressing..."
  echo ""
else
  echo "$0: ${XSRCDIR} does not exist. check it."
  exit 10
fi

if [ -d ${XDMOLDDIR} ]; then
  echo "$0: ${XDMOLDDIR} already exists. clean it before executing me."
  exit 15
fi

#### checking if obj directory exists.
if [ -d ${OBJDIR} ] ; then
  echo "$0: ${OBJDIR} exists."
  if [ -d ${OBJOLDDIR} ] ; then
    echo "$0: ${OBJOLDDIR} exists. remove this before executing me."
    exit 20
  fi

  echo "$0: start cleaning now..."

  echo "$0: disk usage(du -sk ${OBJDIR}/*)"
  du -sk ${OBJDIR}/*
  echo ""

  mkdir -p ${OBJOLDDIR}
  echo "$0: ${OBJDIR} emptied..."
  mv ${OBJDIR}/* ${OBJOLDDIR}
  rm -rf ${OBJOLDDIR}
  echo "$0: ${OBJDIR} emptied...done."

  echo "$0: disk usage(du -sk ${OBJDIR}/*)"
  du -sk ${OBJDIR}/*
  echo ""

else
  echo "$0: ${OBJDIR} does not exist. in-place compilation progressing..."
  EXISTS_OBJDIR="NO"
fi
echo

## I believe xenocara doesn't require tcltk.
## ## i386 architecture requires tcltk-8.3 package
## mach=`/usr/bin/uname -m`
## tkq=`/usr/sbin/pkg_info | grep tk-8.`
## if [ ${mach} = "i386" -a "X${tkq}" = "X" ]; then
##   echo "$0: tk-8.? required on this architecture(${mach})."
##   echo "$0: install tk-8.? package before executing me."
##   echo "$0: see release(8) man page."
##   exit 40
## fi

#### move to src directory
cd ${XSRCDIR}
echo -n "$0: current dir is "
pwd
ls -aFl
echo -n "$0: disk usage(du -sk .) -- "
du -sk .
echo
echo "$0: head Makefile ======"
head Makefile
echo "$0: head Makefile ======"
echo

make bootstrap 

if [  X${EXISTS_OBJDIR} = XYES ]; then
  ## echo "$0: cd to ${OBJDIR} ..."
  ## cd ${OBJDIR}
  ## echo -n "$0: current dir is "
  ## pwd
  ## echo "$0: doing \"lndir\" ..."
  ## lndir ${XSRCDIR}
  make obj
fi

echo -n "$0: moving ${XDMDIR} to ${XDMOLDDIR} ..."
mv ${XDMDIR} ${XDMOLDDIR}
echo -n "$0: \"make build\" start..."
date
make build
date

echo -n "$0: current dir is "
pwd
echo -n "$0: disk usage(du -sk .) -- "
du -sk .
df -k
echo

echo "$0: xenocara compilation finished."
echo "$0: compare files in ${XDMOLDDIR} and in ${XDMDIR} manually."
echo
date

## end_of_file.
