#!/bin/sh
## $Id: make-xf4,v 1.1 2002/12/05 17:04:15 yozo Exp $
## make-xf4 script based on make-x11
## if you wanna record the output, type
##     (make-xf4 >& logfile) &
## and see logfile.
## -- yozo.  Mon May 28 15:59:39 JST 2001
##
## /usr/obj/XF4 can be a mounted partition now.
## -- yozo.  Sun Jun 10 12:03:02 JST 2001
##
## check for tk-8.3 package installation added.
## -- yozo.  Wed Jul  4 05:06:50 JST 2001
##
## checking tk-8.3.3 was too strict,
## relaxing and checking tk-8.3 now -- yozo.  Sun Jan 13 13:48:57 JST 2002

PATH=/sbin:/usr/sbin:/bin:/usr/bin

LOGDIR=/usr/local/tmp
SRCDIR=/usr/XF4
OBJDIR=/usr/obj
OBJOLDDIR=${OBJDIR}/OLD_XF4
OBJBUILDDIR=${OBJDIR}/XF4
EXISTS_OBJDIR="YES" ## assumes obj dir by default
XDMDIR=/etc/X11/xdm
XDMOLDDIR=/etc/X11/xdm_old

echo -n "$0: "
date
echo -n "$0: "
uname -a
echo
ls -alt ${LOGDIR}
df -k
echo

## miscellaneous checking before compiling.
if [ -d ${SRCDIR} ] ; then
  echo "$0: ${SRCDIR} exists. progressing..."
else
  echo "$0: ${SRCDIR} does not exist. check it."
  exit 10
fi

if [ -d ${XDMOLDDIR} ]; then
  echo "$0: ${XDMOLDDIR} already exists. clean it before executing me."
  exit 15
fi

#### checking if obj directory exists.
if [ -d ${OBJDIR} ] ; then
  echo "$0: ${OBJDIR} exists."
  if [ -d ${OBJOLDDIR} ] ; then
    echo "$0: ${OBJOLDDIR} exists. remove this before executing me."
    exit 20
  fi
  if [ -d ${OBJBUILDDIR} ] ; then
    echo "$0: ${OBJBUILDDIR} exists."
    ls -aFl ${OBJBUILDDIR}
    echo "$0: disk usage(du -sk ${OBJBUILDDIR}/*)"
    du -sk ${OBJBUILDDIR}/*
    echo
    ## we have a choice either
    ##   (1) moving and removing background
    ##   (2) removing foreground
    ## "man release" describes (1), but (2) is better sometimes; e.g.,
    ## ${OBJBUILDDIR} and ${OBJOLDDIR} exist on different partitions. 
    echo "$0: start cleaning now..."
    mkdir -p ${OBJOLDDIR}
    ## shell doesn't include dot files here,
    ## but no problem because no dot files exist actually.
    echo "$0: ${OBJBUILDDIR} emptied..."
    mv ${OBJBUILDDIR}/* ${OBJOLDDIR}
    echo "$0: removing ${OBJOLDDIR} directory in background."
    rm -rf ${OBJOLDDIR} &
  else
    echo "$0: ${OBJBUILDDIR} does not exist. mkdir now..."
    mkdir -p ${OBJBUILDDIR}
  fi
  if [ ! -d ${OBJBUILDDIR} ] ; then
    echo "$0: ${OBJBUILDDIR} should exist but can't find it. why??"
    exit 30
  fi
else
  echo "$0: ${OBJDIR} does not exist. in-place compilation progressing..."
  EXISTS_OBJDIR="NO"
fi
echo

## i386 architecture requires tcltk-8.3 package
mach=`/usr/bin/uname -m`
tkq=`/usr/sbin/pkg_info | grep tk-8.3`
if [ ${mach} = "i386" -a "X${tkq}" = "X" ]; then
  echo "$0: tk-8.3 required on this architecture(${mach})."
  echo "$0: install tk-8.3 package before executing me."
  echo "$0: see release(8) man page."
  exit 40
fi

#### move to src directory
cd ${SRCDIR}
echo -n "$0: current dir is "
pwd
ls -aFl
echo -n "$0: disk usage(du -sk .) -- "
du -sk .
echo
echo "$0: head Makefile ======"
head Makefile
echo "$0: head Makefile ======"
echo

if [  X${EXISTS_OBJDIR} = XYES ]; then
  echo "$0: cd to ${OBJBUILDDIR} ..."
  cd ${OBJBUILDDIR}
  echo -n "$0: current dir is "
  pwd
  echo "$0: doing \"lndir\" ..."
  lndir ${SRCDIR}
fi

echo -n "$0: moving ${XDMDIR} to ${XDMOLDDIR} ..."
mv ${XDMDIR} ${XDMOLDDIR}
echo -n "$0: \"make build\" start..."
date
make DESTDIR=/ build
date

echo -n "$0: current dir is "
pwd
echo -n "$0: disk usage(du -sk .) -- "
du -sk .
df -k
echo

echo "$0: XF4 compilation finished."
echo "$0: compare files in ${XDMOLDDIR} and in ${XDMDIR} manually."
echo
date

## end_of_file.
