#!/bin/sh
## $Id: marks,v 1.1.1.1 2002/12/05 17:04:15 yozo Exp $
## list sequences with the number of messages

PATH=/usr/bin:/bin:/usr/local/bin

isrange(){
  ## return 0 if the argument contains "-", e.g., 1-4, 12-30, etc...
  arg=$1
  echo ${arg} | grep -q -- -
}

range (){
  ## echo the range; "range a-b" echos b - a + 1
  expression=`echo $1 | sed 's/\([0-9]*\)-\([0-9]*\)/\2 - \1/'`
  expr 1 + ${expression}
}


mark -list | \
(
  while read line ; do
    seqname=`echo ${line} | awk '{print $1;}' | sed 's/:$//'`
    count=0
    echo -n "${seqname} == "
    for i in `echo ${line} | sed "s/${seqname}://"` ; do
      if isrange ${i}
      then
        rr=`range ${i}`
        count=`expr ${count} + ${rr}`
      else
        count=`expr ${count} + 1`
      fi
    done
    echo "${count}"
  done
)
