#!/bin/sh
## $Id: show_subject,v 1.8 2014/05/05 05:21:45 yozo Exp $
##

progname=`basename "$0"`
flag_debug=0

help(){
  echo "usage: ${progname} messageID"
}

## input: encoded string, e.g., "=?iso-2022-jp?B?.....?="
## output: decoded string
## iso-8859-12 is officially abandoned (see http://en.wikipedia.org/wiki/ISO/IEC_8859)
decode(){
  charset=
  BorQ="B"
  content=
  charset=`echo "$1" | sed 's/^\([^?][^?]*\)?\(.\)?\(.*\)$/\1/'`
  BorQ=`echo "$1" | sed 's/^\([^?][^?]*\)?\(.\)?\(.*\)$/\2/' | tr 'BQ' 'bq'`
  content=`echo "$1" | sed 's/^\([^?][^?]*\)?\(.\)?\(.*\)$/\3/'`
  if [ ${flag_debug} -eq 1 ]; then
    (echo "decode: charset=$charset" 1>&2 )
    (echo "decode: BorQ=$BorQ"  1>&2 )
    (echo "decode: content=$content" 1>&2)
  fi
  if [ "${charset}" = "iso-2022-jp" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-2022-jp-2 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-2022-jp" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-2022-jp-2 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "shift-jis" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f sjis -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "shift-jis" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f sjis -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "euc-jp" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f euc-jp -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "euc-jp" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f euc-jp -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "utf-8" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f utf-8 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "utf-8" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f utf-8 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "gb2312" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f gb2312 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "gb2312" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f gb2312 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "euc-kr" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f euc-kr -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "euc-kr" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f euc-kr -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-1" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-8859-1 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-1" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-8859-1 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-2" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-8859-2 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-2" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-8859-2 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-3" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-8859-3 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-3" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-8859-3 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-4" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-8859-4 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-4" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-8859-4 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-5" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-8859-5 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-5" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-8859-5 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-6" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-8859-6 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-6" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-8859-6 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-7" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-8859-7 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-7" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-8859-7 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-8" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-8859-8 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-8" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-8859-8 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-9" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-8859-9 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-9" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-8859-9 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-10" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-8859-10 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-10" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-8859-10 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-11" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-8859-11 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-11" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-8859-11 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-13" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-8859-13 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-13" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-8859-13 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-14" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-8859-14 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-14" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-8859-14 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-15" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f iso-8859-15 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "iso-8859-15" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f iso-8859-15 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "windows-1253" -a "${BorQ}" = "b" ]; then
    echo "${content}" | base64 -d | iconv -f windows-1253 -t "${MM_CHARSET}" -c
  elif [ "${charset}" = "windows-1253" -a "${BorQ}" = "q" ]; then
    echo "${content}" | qprint -d | iconv -f windows-1253 -t "${MM_CHARSET}" -c
  fi

  return 0
}

## main

case "$1" in
  -h*)
    help
    exit 0
    break
    ;;
  -debug)
   flag_debug=1
    ;;
esac

TMPFILE1=`mktemp /tmp/XXXXXXXXXX` || exit 10
TMPFILE2=`mktemp /tmp/XXXXXXXXXX` || exit 20

sed '/^$/,$d' | sed -n '/^[sS][uU][bB][jJ][eE][cC][tT]:/,$p' > "${TMPFILE1}"

FIRST=`head -1 "${TMPFILE1}" | sed 's/^Subject:[ 	]*//'`
REMAIN=`tail -n +2 < "${TMPFILE1}" | sed '/^[^ 	]/,$d' | sed 's/^[ 	]*//'`

echo "${FIRST}${REMAIN}" | tr -d '\n' > "${TMPFILE1}"
if [ ${flag_debug} -eq 1 ]; then
  cat "${TMPFILE1}" ; echo "\n****************"
fi
cat "${TMPFILE1}" | sed 's/ /\\040/g' |\
          sed -e 's/=?[iI][sS][oO]-2022-[jJ][pP]?\([bBqQ]\)?\([^?][^?]*\)?=/\
ENCODED: iso-2022-jp?\1?\2\
/g' \
              -e 's/=?[eE][uU][cC][-_][jJ][pP]?\([bBqQ]\)?\([^?][^?]*\)?=/\
ENCODED: euc-jp?\1?\2\
/g' \
              -e 's/=?[sS][hH][iI][fF][tT][-_][jJ][iI][sS]?\([bBqQ]\)?\([^?][^?]*\)?=/\
ENCODED: shift-jis?\1?\2\
/g' \
              -e 's/=?[uU][tT][fF]-8?\([bBqQ]\)?\([^?][^?]*\)?=/\
ENCODED: utf-8?\1?\2\
/g' \
              -e 's/=?[gG][bB]2312?\([bBqQ]\)?\([^?][^?]*\)?=/\
ENCODED: gb2312?\1?\2\
/g' \
              -e 's/=?[eE][uU][cC][-_][kK][rR]?\([bBqQ]\)?\([^?][^?]*\)?=/\
ENCODED: euc-kr?\1?\2\
/g' \
              -e 's/=?[iI][sS][oO][-_]8859[-_]\([1-9][0-5]*\)?\([bBqQ]\)?\([^?][^?]*\)?=/\
ENCODED: iso-8859-\1?\2?\3\
/g' \
              -e 's/=?[wW][iI][nN][dD][oO][wW][sS][-_]\([0-9][0-9][0-9][0-9]\)?\([bBqQ]\)?\([^?][^?]*\)?=/\
ENCODED: windows-\1?\2?\3\
/g' \
    > "${TMPFILE2}"

echo "" >> "${TMPFILE2}"

LINE=

cat "${TMPFILE2}" |\
while read LINE; do
  if [ ${flag_debug} -eq 1 ]; then
    (echo "==>${LINE}<==" 1>&2)
  fi
  (echo "${LINE}" | egrep -q '^ENCODED: ') \
                                   && (arg=`echo "${LINE}" | sed 's/^ENCODED: *//'` && decode "$arg"  ) \
                                   || (echo "${LINE}" | sed 's/\040/ /g')
done | tr -d '\n'


echo ""

if [ ${flag_debug} -eq 1 ]; then
  echo "working files ${TMPFILE1} and ${TMPFILE2} left un-removed..." 1>&2
else
  rm "${TMPFILE1}" "${TMPFILE2}"
fi

