#!/bin/sh
## $Id: show_date,v 1.2 2015/05/05 07:44:24 yozo Exp $
##

progname=`basename "$0"`
flag_debug=0

help(){
  echo "usage: ${progname} messageID"
}

## main

case "$1" in
  -h*)
    help
    exit 0
    break
    ;;
  -debug)
   flag_debug=1
    ;;
esac

date_header=`sed '/^$/,$d' | sed -n 's/^[dD][aA][tT][eE]:[ ]*\(.*\)$/\1/p'`

if [ 1 -eq ${flag_debug} ]; then
  echo "DEBUG: date_header == ${date_header}"
fi

## a typical date header looks like "Date: Mon, 13 Apr 2015 17:00:51 +0900"
## Day-of-Week Day-of-Month Month Year ...
## note that Day-of-Week is optional.

## dayom=`echo ${date_header} | awk '{print $2;}' | sed 's/^0*//'`
## month=`echo ${date_header} | awk '{print $3;}' \

dayom=`echo ${date_header} | sed -E 's/^(([a-zA-Z][a-zA-Z][a-zA-Z],)*[ \t]*([1-9]|[12][0-9]|3[01])[ \t]*([a-zA-Z][a-zA-Z][a-zA-Z]).*)$/\3/'`

if [ 1 -eq ${flag_debug} ]; then
  echo "DEBUG: dayofm == ${dayom}"
fi

month=`echo ${date_header} | sed -E 's/^(([a-zA-Z][a-zA-Z][a-zA-Z],)*[ \t]*([1-9]|[12][0-9]|3[01])[ \t]*([a-zA-Z][a-zA-Z][a-zA-Z]).*)$/\4/' \
       | sed -e 's/[jJ][aA][nN]/1/'  \
             -e 's/[fF][eE][bB]/2/'  \
             -e 's/[mM][aA][rR]/3/'  \
             -e 's/[aA][pP][rR]/4/'  \
             -e 's/[mM][aA][yY]/5/'  \
             -e 's/[jJ][uU][nN]/6/'  \
             -e 's/[jJ][uU][lL]/7/'  \
             -e 's/[aA][uU][gG]/8/'  \
             -e 's/[sS][eE][pP]/9/'  \
             -e 's/[oO][cC][tT]/10/' \
             -e 's/[nN][oO][vV]/11/' \
             -e 's/[dD][eE][cC]/12/' `

if [ 1 -eq ${flag_debug} ]; then
  echo "DEBUG: month == ${month}"
fi

printf "%02d/%02d" "${month}" "${dayom}"

