#!/bin/sh
## $Id: smartless,v 1.2 2013/03/19 11:07:27 yozo Exp $
##

LESSCMD=less
TERMINALCHARSET=utf-8 ## assumes the terminal supports utf-8.

if [ -n "${charset}" ]; then
  echo "*** $0 : charset is ${charset} ***"
  iconv -f "${charset}" -t "${TERMINALCHARSET}" < "$1" | "${LESSCMD}"
else
  echo "*** $0 : no charset is specified ***"
  ${LESSCMD} $1
fi

