#!/bin/sh
## $Id: smartless,v 1.3 2013/06/06 16:53:14 yozo Exp $
##

LESSCMD=less

if [ -n "${MM_CHARSET}" ]; then
  TERMINALCHARSET="${MM_CHARSET}" ## nmh assumes MM_CHARSET as terminal's native character set
else
  TERMINALCHARSET=utf-8 ## assumes the terminal supports utf-8 when MM_CHARSET not available
fi

if [ -n "${charset}" ]; then
  echo "*** $0 : charset is ${charset} ***"
  iconv -f "${charset}" -t "${TERMINALCHARSET}" < "$1" | "${LESSCMD}"
else
  echo "*** $0 : no charset is specified ***"
  ${LESSCMD} $1
fi

