#!/bin/sh
## $Id: spamcheck,v 1.6 2011/06/28 18:32:40 yozo Exp $

pick \
  --from nate.com -or --from nownuri -or --from naver.com -or --from yahoo.co.kr -or \
  --from hitel.net -or --from freechal.com -or --from viagr -or --from topliding -or \
  --from biteki-news -or --from paran.com -or --from simmani -or --from hosanna -or \
  --from jubu.com -or --from unitel.co -or --from dreamwiz -or --from postown -or \
  --from querohost.com.br -or --from @mail.ru -or --from hanmir -or --from celeb -or \
  --from @rogers.com -or --from servebbs -or --from paxnet -or --from hananet -or \
  --from uket-ri500 -or --from discount@ -or --from lycos.co.kr -or --from auction -or \
  --from wakaduma -or --from hitoduma -or --from empal -or --from bignews@ -or \
  --from netian.com -or --from hanmail -or --from hanafo -or --from sokuyari -or \
  --from chollian -or --from chol.com -or --from @excite.co.jp -or --from @livedoor.com -or \
  --from infomail@ -or --from @aol.com -or --from @yahoo.co.jp -or --from @live.co.kr -or \
  --subject rolex -or --subject sex -or --subject penis -or --subject viagr -or \
  --subject pharma -or --subject phenterm -or --subject cialis -or --subject pill -or \
  --subject vicodin -or --subject replic -or --subject drug -or --subject valium -or \
  --return-path paran.com -or --return-path hanafo -or --return-path netian.com -or \
  --reply-to dreamwiz -or --reply-to lycos.co.kr -or --reply-to hitel.net -or \
  --to shinkun -or --to kanossa@ -or --to ykoguchi@ -or --to junkers@ -or \
  --to nakasima@ -or --to yumiko@ -or \
  --x-mailer egroups \
  -seq spam
