#!/bin/sh
## $Id: xtermtitle,v 1.1 2002/12/05 17:04:16 yozo Exp $
## xtermtitle: set xterm icon and window title string using escape string.
## see ${X11}/xc/doc/specs/xterm/ctlseqs.ms
## -- yozo.  Thu Sep  2 17:32:49 JST 1999

PATH=/usr/bin
## printf is built-in function of csh.
if [ $# -eq 1 ]; then
  string=$1
  printf "\033]0;${string}\007"
  exit 0
else
  printf "$0: set xterm icon and window title string.\n"
  printf "usage: $0 string\n"
fi
